import logging

from fastapi import APIRouter, HTTPException, status

from schemas.soap_schema import SOAPRequest, SOAPResponse, ErrorResponse
from services.soap_service import generate_soap_note

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/soap",
    tags=["SOAP Notes"],
)


@router.post(
    "",
    response_model=SOAPResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate a structured SOAP note",
    description=(
        "Accepts raw doctor notes and patient demographics, "
        "then returns a structured SOAP note with an ICD-10 diagnosis code "
        "generated by a clinical LLM."
    ),
    responses={
        200: {"description": "SOAP note successfully generated", "model": SOAPResponse},
        422: {"description": "Validation error — missing or invalid input fields"},
        500: {"description": "LLM or server-side error", "model": ErrorResponse},
        503: {"description": "LLM service unavailable or API key missing", "model": ErrorResponse},
    },
)
async def create_soap_note(payload: SOAPRequest) -> SOAPResponse:
    """
    POST /soap

    Converts raw doctor input into a structured SOAP note using an LLM.
    All business logic is handled in `services/soap_service.py`.
    """
    try:
        soap_res = await generate_soap_note(payload)
        
        # Save to DB to generate a sequence case_id
        from db import get_postgres_pool, get_mongo_db
        from services.case_service import save_soap_case
        pg_pool = await get_postgres_pool()
        mongo_db = get_mongo_db()
        saved = await save_soap_case(payload, soap_res, pg_pool, mongo_db)
        
        soap_res.case_id = saved["case_id"]
        return soap_res

    except EnvironmentError as exc:
        # Missing API key or misconfiguration — 503 Service Unavailable
        logger.error("Configuration error: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )

    except RuntimeError as exc:
        # LLM call failure or parse error — 500 Internal Server Error
        logger.error("SOAP generation failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(exc),
        )

    except Exception as exc:
        # Catch-all for unexpected errors
        logger.exception("Unexpected error in POST /soap")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An unexpected error occurred: {exc}",
        )